export interface ArgentineProvince {
  name: string;
  cities: string[];
}

export const ARGENTINE_PROVINCES: ArgentineProvince[] = [
  {
    name: 'Entre Ríos',
    cities: [
      'Basavilbaso',
      'Concepción del Uruguay',
      'Gualeguaychú',
      'Paraná',
      'Concordia',
      'Colón',
      'Villaguay',
      'Gualeguay',
      'Chajarí',
      'Victoria',
      'Nogoyá',
      'Diamante',
      'Santa Elena',
      'Crespo',
      'Federación',
      'Rosario del Tala',
      'San José',
      'Urdinarrain',
      'Villa Elisa',
      'San Salvador',
      'General Ramírez',
      'Viale',
      'Bovril',
      'Hernandarias',
      'Maciá',
      'Lucas González',
      'Larroque',
      'Seguí',
      'Oro Verde',
      'San Benito',
      'Otra localidad...',
    ],
  },
  {
    name: 'Buenos Aires',
    cities: [
      'La Plata',
      'Mar del Plata',
      'Bahía Blanca',
      'Tandil',
      'San Nicolás',
      'Zárate',
      'Campana',
      'Pergamino',
      'Olavarría',
      'Junín',
      'Necochea',
      'Luján',
      'Mercedes',
      'Chivilcoy',
      'Azul',
      'Tres Arroyos',
      'San Pedro',
      'Balcarce',
      'Chascomús',
      'San Antonio de Areco',
      'Pilar',
      'Tigre',
      'San Isidro',
      'Vicente López',
      'Avellaneda',
      'Quilmes',
      'Lanús',
      'Lomas de Zamora',
      'Morón',
      'San Martín',
      'Otra localidad...',
    ],
  },
  {
    name: 'Ciudad Autónoma de Buenos Aires',
    cities: [
      'Agronomía',
      'Almagro',
      'Balvanera',
      'Barracas',
      'Belgrano',
      'Boedo',
      'Caballito',
      'Chacarita',
      'Coghlan',
      'Colegiales',
      'Constitución',
      'Flores',
      'Floresta',
      'La Boca',
      'La Paternal',
      'Liniers',
      'Mataderos',
      'Monte Castro',
      'Montserrat',
      'Nueva Pompeya',
      'Núñez',
      'Palermo',
      'Parque Avellaneda',
      'Parque Chacabuco',
      'Parque Chas',
      'Parque Patricios',
      'Puerto Madero',
      'Recoleta',
      'Retiro',
      'Saavedra',
      'San Cristóbal',
      'San Nicolás',
      'San Telmo',
      'Vélez Sársfield',
      'Versalles',
      'Villa Crespo',
      'Villa del Parque',
      'Villa Devoto',
      'Villa General Mitre',
      'Villa Lugano',
      'Villa Luro',
      'Villa Ortúzar',
      'Villa Pueyrredón',
      'Villa Real',
      'Villa Riachuelo',
      'Villa Santa Rita',
      'Villa Soldati',
      'Villa Urquiza',
      'Otra...',
    ],
  },
  {
    name: 'Santa Fe',
    cities: [
      'Santa Fe',
      'Rosario',
      'Rafaela',
      'Venado Tuerto',
      'Reconquista',
      'Santo Tomé',
      'Villa Gobernador Gálvez',
      'Esperanza',
      'Granadero Baigorria',
      'Casilda',
      'Capitán Bermúdez',
      'San Lorenzo',
      'Cañada de Gómez',
      'Pérez',
      'Avellaneda',
      'Sunchales',
      'Vera',
      'Gálvez',
      'Rufino',
      'San Cristóbal',
      'Otra localidad...',
    ],
  },
  {
    name: 'Córdoba',
    cities: [
      'Córdoba',
      'Río Cuarto',
      'Villa María',
      'Villa Carlos Paz',
      'San Francisco',
      'Alta Gracia',
      'Río Tercero',
      'Bell Ville',
      'La Calera',
      'Jesús María',
      'Villa Dolores',
      'Cruz del Eje',
      'Marcos Juárez',
      'Cosquín',
      'Villa Allende',
      'Arroyito',
      'Laboulaye',
      'Morteros',
      'Las Varillas',
      'La Falda',
      'Otra localidad...',
    ],
  },
  {
    name: 'Corrientes',
    cities: [
      'Corrientes',
      'Goya',
      'Paso de los Libres',
      'Curuzú Cuatiá',
      'Mercedes',
      'Gobernador Virasoro',
      'Bella Vista',
      'Monte Caseros',
      'Santo Tomé',
      'Esquina',
      'Ituzaingó',
      'Santa Lucía',
      'Otra localidad...',
    ],
  },
  {
    name: 'Misiones',
    cities: [
      'Posadas',
      'Oberá',
      'Eldorado',
      'Puerto Iguazú',
      'Apóstoles',
      'Leandro N. Alem',
      'Jardín América',
      'San Vicente',
      'Montecarlo',
      'Puerto Rico',
      'Aristóbulo del Valle',
      'Otra localidad...',
    ],
  },
  {
    name: 'Mendoza',
    cities: [
      'Mendoza',
      'San Rafael',
      'Godoy Cruz',
      'Guaymallén',
      'Las Heras',
      'Luján de Cuyo',
      'Maipú',
      'San Martín',
      'Rivadavia',
      'Tunuyán',
      'General Alvear',
      'Malargüe',
      'Otra localidad...',
    ],
  },
  {
    name: 'Tucumán',
    cities: [
      'San Miguel de Tucumán',
      'Banda del Río Salí',
      'Yerba Buena',
      'Villa Carmela',
      'Concepción',
      'Tafí Viejo',
      'Aguilares',
      'Monteros',
      'Famaillá',
      'Lules',
      'Tafí del Valle',
      'Otra localidad...',
    ],
  },
  {
    name: 'Salta',
    cities: [
      'Salta',
      'San Ramón de la Nueva Orán',
      'Tartagal',
      'General Güemes',
      'San José de Metán',
      'Rosario de la Frontera',
      'Pichanal',
      'Rosario de Lerma',
      'Profesor Salvador Mazza',
      'Colonia Santa Rosa',
      'Cafayate',
      'Otra localidad...',
    ],
  },
  {
    name: 'Chaco',
    cities: [
      'Resistencia',
      'Presidencia Roque Sáenz Peña',
      'Barranqueras',
      'Fontana',
      'Villa Ángela',
      'Castelli',
      'Charata',
      'Quitilipi',
      'Las Breñas',
      'Machagai',
      'General San Martín',
      'Otra localidad...',
    ],
  },
  {
    name: 'San Juan',
    cities: [
      'San Juan',
      'Rawson',
      'Rivadavia',
      'Chimbas',
      'Santa Lucía',
      'Pocito',
      'Caucete',
      'Jáchal',
      'Albardón',
      'Sarmiento',
      'Otra localidad...',
    ],
  },
  {
    name: 'Jujuy',
    cities: [
      'San Salvador de Jujuy',
      'Palpalá',
      'San Pedro de Jujuy',
      'Libertador General San Martín',
      'Perico',
      'La Quiaca',
      'El Carmen',
      'Humahuaca',
      'Tilcara',
      'Otra localidad...',
    ],
  },
  {
    name: 'Río Negro',
    cities: [
      'San Carlos de Bariloche',
      'General Roca',
      'Cipolletti',
      'Viedma',
      'Villa Regina',
      'Cinco Saltos',
      'Catriel',
      'El Bolsón',
      'San Antonio Oeste',
      'Las Grutas',
      'Sierra Grande',
      'Otra localidad...',
    ],
  },
  {
    name: 'Neuquén',
    cities: [
      'Neuquén',
      'Cutral Có',
      'Plottier',
      'Centenario',
      'Zapala',
      'San Martín de los Andes',
      'Plaza Huincul',
      'Chos Malal',
      'Junín de los Andes',
      'Rincón de los Sauces',
      'Villa La Angostura',
      'Otra localidad...',
    ],
  },
  {
    name: 'Formosa',
    cities: [
      'Formosa',
      'Clorinda',
      'Pirané',
      'El Colorado',
      'Las Lomitas',
      'Ibarreta',
      'Comandante Fontana',
      'Pozo del Tigre',
      'Otra localidad...',
    ],
  },
  {
    name: 'Chubut',
    cities: [
      'Comodoro Rivadavia',
      'Trelew',
      'Puerto Madryn',
      'Esquel',
      'Rawson',
      'Sarmiento',
      'Gaiman',
      'Rada Tilly',
      'Trevelin',
      'Dolavon',
      'Otra localidad...',
    ],
  },
  {
    name: 'San Luis',
    cities: [
      'San Luis',
      'Villa Mercedes',
      'Merlo',
      'La Punta',
      'Juana Koslay',
      'Justo Daract',
      'Quines',
      'Santa Rosa de Conlara',
      'Tilisarao',
      'Concarán',
      'Otra localidad...',
    ],
  },
  {
    name: 'Catamarca',
    cities: [
      'San Fernando del Valle de Catamarca',
      'Valle Viejo',
      'Andalgalá',
      'Recreo',
      'Tinogasta',
      'Santa María',
      'Belén',
      'San Isidro',
      'Santa Rosa',
      'Fiambalá',
      'Otra localidad...',
    ],
  },
  {
    name: 'La Rioja',
    cities: [
      'La Rioja',
      'Chilecito',
      'Aimogasta',
      'Chamical',
      'Chepes',
      'Villa Unión',
      'Nonogasta',
      'Famatina',
      'Milagro',
      'Vinchina',
      'Otra localidad...',
    ],
  },
  {
    name: 'Santiago del Estero',
    cities: [
      'Santiago del Estero',
      'La Banda',
      'Termas de Río Hondo',
      'Frías',
      'Añatuya',
      'Fernández',
      'Monte Quemado',
      'Quimilí',
      'Loreto',
      'Clodomira',
      'Suncho Corral',
      'Otra localidad...',
    ],
  },
  {
    name: 'La Pampa',
    cities: [
      'Santa Rosa',
      'General Pico',
      'General Acha',
      'Eduardo Castex',
      'Toay',
      '25 de Mayo',
      'Intendente Alvear',
      'Realicó',
      'Victorica',
      'Guatraché',
      'Macachín',
      'Otra localidad...',
    ],
  },
  {
    name: 'Santa Cruz',
    cities: [
      'Río Gallegos',
      'Caleta Olivia',
      'Pico Truncado',
      'Las Heras',
      'El Calafate',
      'Puerto Deseado',
      'Río Turbio',
      '28 de Noviembre',
      'Perito Moreno',
      'Puerto San Julián',
      'El Chaltén',
      'Otra localidad...',
    ],
  },
  {
    name: 'Tierra del Fuego',
    cities: [
      'Río Grande',
      'Ushuaia',
      'Tolhuin',
      'Otra localidad...',
    ],
  },
];

export const PROVINCE_NAMES = ARGENTINE_PROVINCES.map((p) => p.name);

export function getCitiesForProvince(provinceName: string): string[] {
  const match = ARGENTINE_PROVINCES.find(
    (p) => p.name.toLowerCase() === provinceName.trim().toLowerCase()
  );
  return match ? match.cities : ['Otra localidad...'];
}

/**
 * Valida si un código postal argentino cumple con el formato estándar de 4 dígitos (ej: 3170).
 */
export function isValidPostalCode(postalCode: string | null | undefined): boolean {
  if (!postalCode) return false;
  const clean = postalCode.trim();
  return /^\d{4}$/.test(clean);
}

/**
 * Limpia y restringe el código postal a 4 dígitos numéricos estándar.
 */
export function cleanPostalCode(postalCode: string | null | undefined): string {
  if (!postalCode) return '';
  return postalCode.replace(/\D/g, '').slice(0, 4);
}

